idle_bg = "#2e3440"
idle_fg = "#d8dee9"
info_bg = "#268bd2"
info_fg = "#002b36"
good_bg = "#859900"
good_fg = "#002b36"
warning_bg = "#b58900"
warning_fg = "#002b36"
critical_bg = "#dc322f"
critical_fg = "#002b36"
# separator = "\ue0b2"
separator = ""
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#2e3440"
alternating_tint_fg = "#d8dee9"
